/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.gui;

import javax.swing.JOptionPane;
import universidad.ctrl.Usuario;

/**
 *
 * @author sergi_000
 */
public class MatricularSubgrupo extends javax.swing.JFrame {
    private final Usuario usuario;
    private final TaskCierreMatricula tcm;
    private final Object asignatura;
    private final Object subgroup;

    /**
     * Creates new form informacionSubgrupo
     */
    public MatricularSubgrupo(Usuario usuario, TaskCierreMatricula tcm, Object asignatura, Object subgroup) {
        this.usuario = usuario;
        this.tcm = tcm;
        this.asignatura = asignatura;
        this.subgroup = subgroup;

        initComponents();

        classList.setListData(usuario.getHorarioSubgrupo(subgroup).toArray());
        teacherField.setText(usuario.getProfesorSubgrupo(subgroup).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        classList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        teacherField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        doItButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(classList, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Los horarios asociados a ese subgrupo es:");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel2.setText("Profesor:");
        jPanel1.add(jLabel2);

        teacherField.setEditable(false);
        jPanel1.add(teacherField);

        jPanel2.add(jPanel1);

        doItButton.setText("Matricular");
        doItButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doItButtonActionPerformed(evt);
            }
        });
        jPanel3.add(doItButton);

        backButton.setText("Atrás");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel3.add(backButton);

        jPanel2.add(jPanel3);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(416, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        synchronized (tcm.getLock()) {
            if (tcm.expirado()) {
                return;
            }

            dispose();
            SeleccionarSubgrupo frame = new SeleccionarSubgrupo(usuario, tcm, asignatura);
            frame.setVisible(true);
            tcm.setVentanaActual(frame);
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void doItButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doItButtonActionPerformed
        if (usuario.matricularSubgrupo(subgroup)) {
            JOptionPane.showMessageDialog(this, "Te has dado de alta correctamente en el subgrupo seleccionado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se te ha podido inscribir en el grupo porque está completo", "Error", JOptionPane.ERROR_MESSAGE);
        }

        synchronized (tcm.getLock()) {
            if (tcm.expirado()) {
                return;
            }

            dispose();
            SeleccionarAsignatura frame = new SeleccionarAsignatura(usuario, tcm);
            frame.setVisible(true);
            tcm.setVentanaActual(frame);
        }
    }//GEN-LAST:event_doItButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JList classList;
    private javax.swing.JButton doItButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField teacherField;
    // End of variables declaration//GEN-END:variables
}
