/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.gui;

import java.util.Timer;
import javax.swing.JOptionPane;
import universidad.ctrl.Usuario;

/**
 *
 * @author sergi_000
 */
public class SeleccionarAsignatura extends javax.swing.JFrame {
    private final Usuario usuario;
    private final TaskCierreMatricula taskCierreMatriculacion;

    /**
     * Creates new form seleccionarAsignatura
     */
    public SeleccionarAsignatura(Usuario usuario, TaskCierreMatricula taskCierreMatriculacion) {
        this.usuario = usuario;
        this.taskCierreMatriculacion = taskCierreMatriculacion;
        taskCierreMatriculacion.setVentanaActual(this);

        initComponents();

        asigList.setListData(usuario.listarAsignaturasTitulacionAlumno().toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        continueButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        asigList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione una de las asignaturas de las que se puede matricular:");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        continueButton.setText("Continuar");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        jPanel1.add(continueButton);

        backButton.setText("Atrás");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(asigList, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(567, 348));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        Object asig = asigList.getSelectedValue();
        if (asig == null) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna asignatura", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (usuario.estaAlumnoMatriculado(asig)) {
            JOptionPane.showMessageDialog(this, "Ya te encuentras registrado en la asignatura escogida", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        synchronized (taskCierreMatriculacion.getLock()) {
            if (taskCierreMatriculacion.expirado()) {
                return;
            }

            dispose();
            SeleccionarSubgrupo frame = new SeleccionarSubgrupo(usuario, taskCierreMatriculacion, asig);
            frame.setVisible(true);
            taskCierreMatriculacion.setVentanaActual(frame);
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        synchronized (taskCierreMatriculacion.getLock()) {
            taskCierreMatriculacion.cancel();
        }

        dispose();
        new VistaAlumno(usuario).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList asigList;
    private javax.swing.JButton backButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
