/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.gui;

import javax.swing.JOptionPane;
import universidad.ctrl.Usuario;

/**
 *
 * @author sergi_000
 */
public class SeleccionarSubgrupo extends javax.swing.JFrame {
    private final Usuario usuario;
    private final TaskCierreMatricula tcm;
    private final Object asignatura;

    /**
     * Creates new form seleccionarSubgrupo
     */
    public SeleccionarSubgrupo(Usuario usuario, TaskCierreMatricula tcm, Object asignatura) {
        this.usuario = usuario;
        this.tcm = tcm;
        this.asignatura = asignatura;

        initComponents();

        subgroupList.setListData(usuario.getSubgruposAsignatura(asignatura).toArray());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        subgroupList = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        continueButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Escoger Subgrupo"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selecciona el subgrupo que quieras:");
        getContentPane().add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setViewportView(subgroupList);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        continueButton.setText("Continuar");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });
        jPanel1.add(continueButton);

        backButton.setText("Atrás");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(567, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
        Object subgroup = subgroupList.getSelectedValue();
        if (subgroup == null) {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún subgrupo", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        synchronized (tcm.getLock()) {
            if (tcm.expirado()) {
                return;
            }

            dispose();
            MatricularSubgrupo frame = new MatricularSubgrupo(usuario, tcm, asignatura, subgroup);
            frame.setVisible(true);
            tcm.setVentanaActual(frame);
        }
    }//GEN-LAST:event_continueButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        synchronized (tcm.getLock()) {
            if (tcm.expirado()) {
                return;
            }

            dispose();
            SeleccionarAsignatura frame = new SeleccionarAsignatura(usuario, tcm);
            frame.setVisible(true);
            tcm.setVentanaActual(frame);
        }
    }//GEN-LAST:event_backButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList subgroupList;
    // End of variables declaration//GEN-END:variables
}
