/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidad.gui;

import javax.swing.JOptionPane;
import universidad.ctrl.Usuario;

/**
 *
 * @author sergi_000
 */
public class SubgrupoAsignatura extends javax.swing.JFrame {
    private final Usuario usuario;
    private final Object asignatura;
    
    SubgrupoAsignatura(Usuario usuario, Object asig) {
        initComponents();
        this.usuario = usuario;
        this.asignatura = asig;
        subgroupList.setListData(usuario.getSubgruposAsignatura(asignatura).toArray());    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        contButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        subgroupList = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Selecciona el subgrupo que quieras:");
        getContentPane().add(jLabel3, java.awt.BorderLayout.PAGE_START);

        contButton.setText("Continuar");
        contButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contButtonActionPerformed(evt);
            }
        });
        jPanel1.add(contButton);

        backButton.setText("Atras");
        backButton.setActionCommand("Atrás");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        jPanel1.add(backButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(subgroupList, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(628, 371));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        new ListadoAsignaturas(usuario).setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void contButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contButtonActionPerformed
        Object subgroup = subgroupList.getSelectedValue();
        if (subgroup != null) {
            new InformacionSubgrupo(usuario, asignatura, subgroup).setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún subgrupo", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_contButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton contButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JList subgroupList;
    // End of variables declaration//GEN-END:variables
}
