
test_tabla:
	g++ -Wall alumno.cpp tabla.cpp test_tabla.cpp -o test_tabla

costes:
	g++ -Wall alumno.cpp tabla.cpp abb.cpp costes.cpp -o costes

clean:
	$(RM) *.o
	$(RM) test_tabla test_tabla.exe
	$(RM) costes costes.exe
