
test_arbol:
    g++ -Wall abb.cpp alumno.cpp test_arbol.cpp -o test_arbol

test_map:
    g++ -Wall abb.cpp alumno.cpp test_map.cpp -o test_map

all: test_arbol test_map

clean:
    $(RM) *.o
    $(RM) test_arbol test_arbol.exe
    $(RM) test_map test_map.exe
